### ISSUE TITLE
Odd model_from_url() behavior

### ISSUE THREAD

**Issue by SK83RJOSH** [AmbientOrg/Ambient#111]
### Behavior differs when running via `kiwi run` and `kiwi join`

When running a project through `kiwi run` the following code works:
```rust
    make_transformable()
        .with(model_from_url(), "assets/test.glb/models/main.json".to_string())
```

However, when running through `kiwi serve` any clients that join fail to load the corresponding model.

If the above code snippet is changed to:
```rust
    make_transformable()
        .with(model_from_url(), "assets/assets/test.glb/models/main.json".to_string())
```

The model will now load when `kiwi join` is used but _not_ when `kiwi run` is used.

### Behavior differs from `object_from_url()`

Creating an object with the following code snippet works:
```rust
    make_transformable()
        .with(object_from_url(), "assets/test.glb".to_string())
```

But it does _not_ work with the following code snippet:
```rust
    make_transformable()
        .with(model_from_url(), "assets/test.glb".to_string())
```

This appears to be an oversight, and should probably be fixed to ensure behavior is consistent between the two components. 🙂

**Comment by FredrikNoren** [comment]
I'll implement #100 first of all, then this will be easier to debug

**Comment by FredrikNoren** [comment]
@SK83RJOSH #100 is implemented now, so should be a bit easier to debug exactly what's going wrong now. Also, the endpoint is changed to `content`, so it should give you something like `http://localhost:8999/content/assets/test.glb`

**Comment by SK83RJOSH** [comment]
@FredrikNoren that fixes the inconsistency between running via run/serve/join! I still need to specify the full path to models/main.json. Not 100% necessary, but I'd love for that to get the same treatment as `object_from_url` to reduce the chances of papercuts. :)

**Comment by FredrikNoren** [comment]
@SK83RJOSH Ok great! Hm yup it should probably do that, the only reason it doesn't right now is because there might be multiple scenes in the model doc, but it could just append that last bit if it doesn't contain `/models/` or something.

**Comment by SK83RJOSH** [comment]
I'd be content with that! That's more or less what's done for models so it'll be consistent from the lazy developer standpoint ^^
